### ISSUE TITLE
Current nvidia-container-toolkit not working with current nvidia-drivers (435.21 or 440.31)

### ISSUE THREAD

**Issue by ahmedmagdiosman** [pop-os/nvidia-container-toolkit#1]
See https://github.com/pop-os/nvidia-graphics-drivers/issues/31 and https://github.com/NVIDIA/nvidia-docker/issues/1114 .

Current workaround: use NVIDIA's official container-toolkit.

### 1. Add the repo
```bash
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
```

### 2. Then pin the repo by creating:

 /etc/apt/preferences.d/nvidia-docker-pin-1002
```bash
Package: *
Pin: origin nvidia.github.io 
Pin-Priority: 1002
```

### 3. Install the driver 
```bash
sudo apt install nvidia-driver-440
```
### 5. Install nvidia-container-toolkit and restart docker
```bash
sudo apt install nvidia-container-toolkit

systemctl restart docker
```

**Comment by wilderrodrigues** [comment]
I followed your steps and got my RTX-2080 working just fine. Thanks a lot!

**Comment by hemingchen** [comment]
Had the same issue with my GTX-1080Ti, followed above steps and it now works fine. Thanks!

**Comment by gussmith** [comment]
Had the same issue with RTX2070 on Pop_OS. 
I just did this after pinning the NVIDIA as shown above and only did: 
**sudo apt install nvidia-container-toolkit**
And it is now,thank god! working finally!

**Comment by ids1024** [comment]
The version packaged by Pop!_OS has been updated, so this should be fixed now.

**Comment by dysonsphere-startmail** [comment]
`curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
is met with:
```# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
```
`cd /etc/os-release` returns:
`bash: cd: /etc/os-release: Not a directory`

**Comment by mmstick** [comment]
@dysonsphere-startmail That's not our repository. This package is in the Pop PPA

**Comment by mmstick** [comment]
Closing because this was 3 years ago
