### ISSUE TITLE
Failed to run nvidia container

### ISSUE THREAD

**Issue by yuanbing** [pop-os/nvidia-container-toolkit#2]
I got this error when I tried to run the nvidia docker container:

1. **_docker run --gpus all nvidia/cuda:10.0-base nvidia-smi_**

docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: detection error: driver error: failed to process request\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled 

2. output of nvidia-container-cli

**_nvidia-container-cli -k -d /dev/tty info_**

-- WARNING, the following logs are for debugging purposes only --

I0115 09:20:37.294036 4304 nvc.c:281] initializing library context (version=1.0.6, build=0000000000000000000000000000000000000000)
I0115 09:20:37.294142 4304 nvc.c:255] using root /
I0115 09:20:37.294166 4304 nvc.c:256] using ldcache /etc/ld.so.cache
I0115 09:20:37.294182 4304 nvc.c:257] using unprivileged user 1000:1000
W0115 09:20:37.297221 4305 nvc.c:186] failed to set inheritable capabilities
W0115 09:20:37.297314 4305 nvc.c:187] skipping kernel modules load due to failure
I0115 09:20:37.297949 4306 driver.c:133] starting driver service
I0115 09:20:37.340783 4304 nvc_info.c:437] requesting driver information with ''
nvidia-container-cli: detection error: driver error: failed to process request
I0115 09:20:37.341021 4304 nvc.c:318] shutting down library context
W0115 09:20:37.351295 4304 driver.c:220] terminating driver service (forced)
I0115 09:20:37.483188 4304 driver.c:233] driver service terminated with signal 9

3. output of nvidia-smi -a

**_nvidia-smi -a_**

==============NVSMI LOG==============

Timestamp                           : Wed Jan 15 17:21:42 2020
Driver Version                      : 440.44
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:04:00.0
    Product Name                    : GeForce GTX 1060 6GB
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-ce0f01b1-4ce8-cedf-87bd-a1dd645be8d7
    Minor Number                    : 0
    VBIOS Version                   : 86.06.27.00.9B
    MultiGPU Board                  : No
    Board ID                        : 0x400
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : None
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x04
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1C0310DE
        Bus Id                      : 00000000:04:00.0
        Sub System Id               : 0x85B61043
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 1000 KB/s
        Rx Throughput               : 1000 KB/s
    Fan Speed                       : 0 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 6070 MiB
        Used                        : 583 MiB
        Free                        : 5487 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 14 MiB
        Free                        : 242 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 3 %
        Memory                      : 4 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending Page Blacklist      : N/A
    Temperature
        GPU Current Temp            : 32 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 99 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 9.43 W
        Power Limit                 : 120.00 W
        Default Power Limit         : 120.00 W
        Enforced Power Limit        : 120.00 W
        Min Power Limit             : 60.00 W
        Max Power Limit             : 140.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 4004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1573
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 95 MiB
        Process ID                  : 3412
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 158 MiB
        Process ID                  : 3656
            Type                    : G
            Name                    : /usr/bin/gnome-shellnvidia-smi -a

==============NVSMI LOG==============

Timestamp                           : Wed Jan 15 17:21:42 2020
Driver Version                      : 440.44
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:04:00.0
    Product Name                    : GeForce GTX 1060 6GB
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-ce0f01b1-4ce8-cedf-87bd-a1dd645be8d7
    Minor Number                    : 0
    VBIOS Version                   : 86.06.27.00.9B
    MultiGPU Board                  : No
    Board ID                        : 0x400
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.03
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : None
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x04
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1C0310DE
        Bus Id                      : 00000000:04:00.0
        Sub System Id               : 0x85B61043
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 1000 KB/s
        Rx Throughput               : 1000 KB/s
    Fan Speed                       : 0 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 6070 MiB
        Used                        : 583 MiB
        Free                        : 5487 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 14 MiB
        Free                        : 242 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 3 %
        Memory                      : 4 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending Page Blacklist      : N/A
    Temperature
        GPU Current Temp            : 32 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 99 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 9.43 W
        Power Limit                 : 120.00 W
        Default Power Limit         : 120.00 W
        Enforced Power Limit        : 120.00 W
        Min Power Limit             : 60.00 W
        Max Power Limit             : 140.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 4004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1573
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 95 MiB
        Process ID                  : 3412
            Type                    : G
            Name                    : /usr/lib/xorg/Xorg
            Used GPU Memory         : 158 MiB
        Process ID                  : 3656
            Type                    : G
            Name                    : /usr/bin/gnome-shell
            Used GPU Memory         : 152 MiB
        Process ID                  : 9323
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=6741434274533593519,9565514079066516768,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=16605780180680635404
            Used GPU Memory         : 165 MiB

            Used GPU Memory         : 152 MiB
        Process ID                  : 9323
            Type                    : G
            Name                    : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=6741434274533593519,9565514079066516768,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=16605780180680635404
            Used GPU Memory         : 165 MiB

4. output of uname:

**_uname -a_**
Linux byuan-desktop 5.3.0-7625-generic #27~1576337086~18.04~787b29e-Ubuntu SMP Sat Dec 14 18:28:42 UTC  x86_64 x86_64 x86_64 GNU/Linux

Need help!!!

**Comment by ahmedmagdiosman** [comment]
Seems like the same issue I had here https://github.com/pop-os/nvidia-container-toolkit/issues/1

**Comment by torben-w** [comment]
I get the same error even with following the instructions in #1

**Comment by dysonsphere-startmail** [comment]
I get a different error:
Running
`docker run --gpus all nvidia/cuda:11.1-base nvidia-smi`
I get:
`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]`

When I try to install from NVIDIA as in #1:
`curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
I get:
```
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
```
My distribution as per `uname -a` is:
`
Linux pop-os 5.8.0-7625-generic #26~1603389471~20.04~f6b125f-Ubuntu SMP Thu Oct 22 20:35:49 UTC  x86_64 x86_64 x86_64 GNU/Linux`

output of nvidia-container-cli as per `nvidia-container-cli -k -d /dev/tty info` is:
```
-- WARNING, the following logs are for debugging purposes only --

I1110 19:06:10.474108 84378 nvc.c:282] initializing library context (version=1.3.0, build=0000000000000000000000000000000000000000)
I1110 19:06:10.474169 84378 nvc.c:256] using root /
I1110 19:06:10.474178 84378 nvc.c:257] using ldcache /etc/ld.so.cache
I1110 19:06:10.474186 84378 nvc.c:258] using unprivileged user 1000:1000
I1110 19:06:10.474212 84378 nvc.c:299] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I1110 19:06:10.474363 84378 nvc.c:301] dxcore initialization failed, continuing assuming a non-WSL environment
W1110 19:06:10.475888 84379 nvc.c:187] failed to set inheritable capabilities
W1110 19:06:10.475945 84379 nvc.c:188] skipping kernel modules load due to failure
I1110 19:06:10.476263 84380 driver.c:101] starting driver service
I1110 19:06:10.512374 84378 nvc_info.c:680] requesting driver information with ''
I1110 19:06:10.514498 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvoptix.so.455.28
I1110 19:06:10.514731 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.455.28
I1110 19:06:10.515203 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.455.28
I1110 19:06:10.517204 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.455.28
I1110 19:06:10.517442 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.455.28
I1110 19:06:10.517905 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.455.28
I1110 19:06:10.518241 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.455.28
I1110 19:06:10.518285 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.455.28
I1110 19:06:10.518738 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.455.28
I1110 19:06:10.519024 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.455.28
I1110 19:06:10.519338 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.455.28
I1110 19:06:10.519619 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.455.28
I1110 19:06:10.519909 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.455.28
I1110 19:06:10.520167 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.455.28
I1110 19:06:10.520622 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.455.28
I1110 19:06:10.520916 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.455.28
I1110 19:06:10.520970 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.455.28
I1110 19:06:10.521307 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.455.28
I1110 19:06:10.521558 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.455.28
I1110 19:06:10.521866 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.455.28
I1110 19:06:10.522131 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libcuda.so.455.28
I1110 19:06:10.522504 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.455.28
I1110 19:06:10.522846 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.455.28
I1110 19:06:10.523062 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.455.28
I1110 19:06:10.523351 84378 nvc_info.c:169] selecting /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.455.28
I1110 19:06:10.526908 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-tls.so.455.28
I1110 19:06:10.527737 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-ptxjitcompiler.so.455.28
I1110 19:06:10.528160 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-opticalflow.so.455.28
I1110 19:06:10.528618 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-opencl.so.455.28
I1110 19:06:10.529426 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-ml.so.455.28
I1110 19:06:10.530670 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-ifr.so.455.28
I1110 19:06:10.530998 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-glvkspirv.so.455.28
I1110 19:06:10.531295 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-glsi.so.455.28
I1110 19:06:10.531925 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-glcore.so.455.28
I1110 19:06:10.532204 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-fbc.so.455.28
I1110 19:06:10.532465 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-encode.so.455.28
I1110 19:06:10.532809 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-eglcore.so.455.28
I1110 19:06:10.533102 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvidia-compiler.so.455.28
I1110 19:06:10.533371 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libnvcuvid.so.455.28
I1110 19:06:10.534303 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libcuda.so.455.28
I1110 19:06:10.534628 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libGLX_nvidia.so.455.28
I1110 19:06:10.534871 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libGLESv2_nvidia.so.455.28
I1110 19:06:10.535086 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libGLESv1_CM_nvidia.so.455.28
I1110 19:06:10.535399 84378 nvc_info.c:169] selecting /usr/lib/i386-linux-gnu/libEGL_nvidia.so.455.28
W1110 19:06:10.535424 84378 nvc_info.c:350] missing library libnvidia-fatbinaryloader.so
W1110 19:06:10.535429 84378 nvc_info.c:350] missing library libvdpau_nvidia.so
W1110 19:06:10.535434 84378 nvc_info.c:354] missing compat32 library libnvidia-cfg.so
W1110 19:06:10.535438 84378 nvc_info.c:354] missing compat32 library libnvidia-fatbinaryloader.so
W1110 19:06:10.535444 84378 nvc_info.c:354] missing compat32 library libnvidia-allocator.so
W1110 19:06:10.535450 84378 nvc_info.c:354] missing compat32 library libnvidia-ngx.so
W1110 19:06:10.535455 84378 nvc_info.c:354] missing compat32 library libvdpau_nvidia.so
W1110 19:06:10.535460 84378 nvc_info.c:354] missing compat32 library libnvidia-rtcore.so
W1110 19:06:10.535465 84378 nvc_info.c:354] missing compat32 library libnvoptix.so
W1110 19:06:10.535469 84378 nvc_info.c:354] missing compat32 library libnvidia-cbl.so
I1110 19:06:10.535893 84378 nvc_info.c:276] selecting /usr/bin/nvidia-smi
I1110 19:06:10.535917 84378 nvc_info.c:276] selecting /usr/bin/nvidia-debugdump
I1110 19:06:10.535936 84378 nvc_info.c:276] selecting /usr/bin/nvidia-persistenced
I1110 19:06:10.535959 84378 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-control
I1110 19:06:10.536139 84378 nvc_info.c:276] selecting /usr/bin/nvidia-cuda-mps-server
I1110 19:06:10.536166 84378 nvc_info.c:438] listing device /dev/nvidiactl
I1110 19:06:10.536171 84378 nvc_info.c:438] listing device /dev/nvidia-uvm
I1110 19:06:10.536175 84378 nvc_info.c:438] listing device /dev/nvidia-uvm-tools
I1110 19:06:10.536179 84378 nvc_info.c:438] listing device /dev/nvidia-modeset
I1110 19:06:10.536205 84378 nvc_info.c:317] listing ipc /run/nvidia-persistenced/socket
W1110 19:06:10.536562 84378 nvc_info.c:321] missing ipc /tmp/nvidia-mps
I1110 19:06:10.536571 84378 nvc_info.c:745] requesting device information with ''
I1110 19:06:10.543273 84378 nvc_info.c:628] listing device /dev/nvidia0 (GPU-730c2eef-a053-bac8-2a0d-c409261079e5 at 00000000:01:00.0)
NVRM version:   455.28
CUDA version:   11.1

Device Index:   0
Device Minor:   0
Model:          GeForce MX130
Brand:          GeForce
GPU UUID:       GPU-730c2eef-a053-bac8-2a0d-c409261079e5
Bus Location:   00000000:01:00.0
Architecture:   5.0
I1110 19:06:10.543306 84378 nvc.c:337] shutting down library context
I1110 19:06:10.543633 84380 driver.c:156] terminating driver service
I1110 19:06:10.544067 84378 driver.c:194] driver service terminated successfully
```
output of `nvidia-smi -a` is:
```
==============NVSMI LOG==============

Timestamp                                 : Tue Nov 10 14:08:36 2020
Driver Version                            : 455.28
CUDA Version                              : 11.1

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Product Name                          : GeForce MX130
    Product Brand                         : GeForce
    Display Mode                          : Disabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-730c2eef-a053-bac8-2a0d-c409261079e5
    Minor Number                          : 0
    VBIOS Version                         : 82.08.77.00.CB
    MultiGPU Board                        : No
    Board ID                              : 0x100
    GPU Part Number                       : N/A
    Inforom Version
        Image Version                     : N/A
        OEM Object                        : N/A
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x01
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x174D10DE
        Bus Id                            : 00000000:01:00.0
        Sub System Id                     : 0x08191028
        GPU Link Info
            PCIe Generation
                Max                       : 3
                Current                   : 2
            Link Width
                Max                       : 4x
                Current                   : 4x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 671000 KB/s
        Rx Throughput                     : 9000 KB/s
    Fan Speed                             : N/A
    Performance State                     : P5
    Clocks Throttle Reasons
        Idle                              : Not Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : N/A
            HW Power Brake Slowdown       : N/A
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 2004 MiB
        Used                              : 416 MiB
        Free                              : 1588 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 3 MiB
        Free                              : 253 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 13 %
        Memory                            : 6 %
        Encoder                           : N/A
        Decoder                           : N/A
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
            Double Bit            
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
        Aggregate
            Single Bit            
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
            Double Bit            
                Device Memory             : N/A
                Register File             : N/A
                L1 Cache                  : N/A
                L2 Cache                  : N/A
                Texture Memory            : N/A
                Texture Shared            : N/A
                CBU                       : N/A
                Total                     : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 51 C
        GPU Shutdown Temp                 : 99 C
        GPU Slowdown Temp                 : 94 C
        GPU Max Operating Temp            : 90 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    Power Readings
        Power Management                  : N/A
        Power Draw                        : N/A
        Power Limit                       : N/A
        Default Power Limit               : N/A
        Enforced Power Limit              : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    Clocks
        Graphics                          : 823 MHz
        SM                                : 823 MHz
        Memory                            : 800 MHz
        Video                             : 807 MHz
    Applications Clocks
        Graphics                          : 1110 MHz
        Memory                            : 2505 MHz
    Default Applications Clocks
        Graphics                          : 1108 MHz
        Memory                            : 2505 MHz
    Max Clocks
        Graphics                          : 1189 MHz
        SM                                : 1189 MHz
        Memory                            : 2505 MHz
        Video                             : 1165 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Processes
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 1342
            Type                          : G
            Name                          : /usr/lib/xorg/Xorg
            Used GPU Memory               : 71 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 2358
            Type                          : G
            Name                          : /usr/lib/xorg/Xorg
            Used GPU Memory               : 223 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 2558
            Type                          : G
            Name                          : /usr/bin/gnome-shell
            Used GPU Memory               : 59 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 2786
            Type                          : G
            Name                          : /home/m3coordinator/Apps/Nextcloud/Nextcloud-3.0.3-x86_64.AppImage
            Used GPU Memory               : 23 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 3025
            Type                          : G
            Name                          : /usr/lib/slack/slack --type=gpu-process --field-trial-handle=14731566576066503262,7359784610108963128,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,HardwareMediaKeyHandling,SameSiteByDefaultCookies,SpareRendererForSitePerProcess,WebRtcHideLocalIpsWithMdns --gpu-preferences=MAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA= --shared-files
            Used GPU Memory               : 18 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 55716
            Type                          : G
            Name                          : /app/lib/firefox/firefox-bin
            Used GPU Memory               : 0 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 58415
            Type                          : G
            Name                          : /usr/bin/anydesk
            Used GPU Memory               : 5 MiB
```

**Comment by mmstick** [comment]
Closing this because it was 2 years ago
